uv4l --auto-video_nr --driver raspicam --encoding mjpeg --server-option '--enable-www-server=yes' \
--server-option '--www-port=443' \
--server-option '--enable-webrtc-video=yes' \
--server-option '--enable-webrtc-audio=no' \
--server-option '--webrtc-receive-datachannels=yes' \
--server-option '--webrtc-receive-audio=yes' \
--server-option '--www-use-ssl=yes' \
--server-option '--www-ssl-private-key-file=/etc/letsencrypt/live/www.ssmackey.org/privkey.pem' \
--server-option '--www-ssl-certificate-file=/etc/letsencrypt/live/www.ssmackey.org/fullchain.pem' \
--server-option '--www-root-path=/home/pi/ccs/' \
--server-option '--www-webrtc-signaling-path=/webrtc' \
#--server-option '--webrtc-renderer-fullscreen=yes'
